"""Test full LLM-assisted classification pipeline against synthetic files.

Runs classify_document (Flow 2) + normalization on a diverse subset of
~10 synthetic files generated by tests/generate_synthetic_files.py.
Writes results to tests/generated_files/results_llm.csv.

Usage:
    pytest tests/test_llm_import.py -m llm -s -v
    pytest tests/test_llm_import.py -m llm -s -v --tb=short
"""
from __future__ import annotations

import csv
import sys
from dataclasses import dataclass
from pathlib import Path

import pandas as pd
import pytest

# ── project root on sys.path ─────────────────────────────────────────────
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from core.classifier import classify_document
from core.llm_backends import BackendFactory
from core.orchestrator import ProcessingConfig, _build_backend, load_raw_dataframe, _normalize_df_with_schema

GENERATED_DIR = Path(__file__).resolve().parent / "generated_files"
MANIFEST_PATH = GENERATED_DIR / "manifest.csv"
RESULTS_PATH = GENERATED_DIR / "results_llm.csv"

# ── Amount-format to SignConvention mapping ──────────────────────────────
# The manifest uses: signed_single, debit_credit_split, debit_credit_signed, positive_only
# The codebase uses: signed_single, debit_positive, credit_negative
_AMOUNT_FORMAT_TO_SIGN_CONVENTION = {
    "signed_single": "signed_single",
    "positive_only": "signed_single",        # positive_only => signed_single + invert_sign
    "debit_credit_split": "debit_positive",
    "debit_credit_signed": "credit_negative",
}


# ── Diverse subset of ~10 files ─────────────────────────────────────────
# Selection criteria: CSV + XLSX, all 4 amount formats, various header sizes
# (0, 3, 5, 7, 10, 12, 14, 15), bank_account + credit_card + debit_card + savings
_SELECTED_FILES = [
    # bank_account, CSV, signed_single, headers=10
    "CC-1_S_000.csv",
    # bank_account, XLSX, debit_credit_split, headers=10
    "CC-1_M_001.xlsx",
    # bank_account, CSV, debit_credit_signed, headers=0
    "CC-1_L_002.csv",
    # credit_card, XLSX, positive_only, headers=5
    "CRED-1_M_010.xlsx",
    # credit_card, CSV, positive_only, headers=12
    "CRED-2_S_012.csv",
    # debit_card, CSV, signed_single, headers=0
    "RIC-1_S_015.csv",
    # debit_card, XLSX, debit_credit_split, headers=7
    "RIC-2_M_019.xlsx",
    # debit_card, CSV, debit_credit_signed, headers=0
    "RIC-3_L_023.csv",
    # savings_account, CSV, signed_single, headers=0
    "RISP-1_S_024.csv",
    # bank_account, XLSX, headers=15
    "CC-1_V_027.xlsx",
]


@dataclass
class FileResult:
    """Result of classifying and normalizing one file."""
    filename: str
    doc_type_expected: str
    doc_type_detected: str
    doc_type_match: bool
    confidence_score: float
    convention_expected: str
    convention_detected: str
    convention_match: bool
    n_rows_expected: int
    n_rows_parsed: int
    normalization_rate: float
    amount_success_rate: float
    date_success_rate: float
    # Column mapping details
    date_col_found: bool
    amount_cols_found: bool
    description_col_found: bool


def _load_manifest() -> dict[str, dict]:
    """Load manifest.csv into a dict keyed by filename."""
    rows = {}
    with open(MANIFEST_PATH, encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows[row["filename"]] = row
    return rows


def _run_classification(manifest: dict[str, dict]) -> list[FileResult]:
    """Run classify_document + normalize on selected files."""
    config = ProcessingConfig()
    backend = _build_backend(config)

    results: list[FileResult] = []

    for filename in _SELECTED_FILES:
        if filename not in manifest:
            print(f"  SKIP {filename}: not in manifest")
            continue

        filepath = GENERATED_DIR / filename
        if not filepath.exists():
            print(f"  SKIP {filename}: file not found")
            continue

        meta = manifest[filename]
        n_data_expected = int(meta["n_data_rows"])
        doc_type_expected = meta["doc_type"]
        amount_format = meta["amount_format"]
        convention_expected = _AMOUNT_FORMAT_TO_SIGN_CONVENTION[amount_format]
        has_split = meta["has_debit_credit_split"] == "true"

        print(f"\n{'='*60}")
        print(f"  Processing: {filename}")
        print(f"  Expected: doc_type={doc_type_expected}, convention={convention_expected}, rows={n_data_expected}")

        # 1. Load raw DataFrame
        raw_bytes = filepath.read_bytes()
        df, encoding, preprocess_info = load_raw_dataframe(raw_bytes, filename)

        print(f"  Loaded: {len(df)} rows, {len(df.columns)} cols, skipped={preprocess_info.skipped_rows}")

        # 2. Classify via LLM
        schema = classify_document(
            df_raw=df,
            llm_backend=backend,
            source_name=filename,
            sanitize=True,
            header_certain=preprocess_info.header_certain,
        )

        if schema is None:
            print(f"  FAIL: classify_document returned None")
            results.append(FileResult(
                filename=filename,
                doc_type_expected=doc_type_expected,
                doc_type_detected="NONE",
                doc_type_match=False,
                confidence_score=0.0,
                convention_expected=convention_expected,
                convention_detected="NONE",
                convention_match=False,
                n_rows_expected=n_data_expected,
                n_rows_parsed=0,
                normalization_rate=0.0,
                amount_success_rate=0.0,
                date_success_rate=0.0,
                date_col_found=False,
                amount_cols_found=False,
                description_col_found=False,
            ))
            continue

        # Extract detected values
        doc_type_detected = schema.doc_type.value if hasattr(schema.doc_type, "value") else str(schema.doc_type)
        convention_detected = schema.sign_convention.value if hasattr(schema.sign_convention, "value") else str(schema.sign_convention)
        confidence_score = getattr(schema, "confidence_score", 0.0)

        doc_type_match = doc_type_detected == doc_type_expected

        # Convention matching: for positive_only files, the pipeline should detect
        # signed_single + invert_sign=True. We accept that as a match.
        if amount_format == "positive_only":
            convention_match = (
                convention_detected == "signed_single" and getattr(schema, "invert_sign", False)
            )
        else:
            convention_match = convention_detected == convention_expected

        # Column mapping checks
        date_col_found = bool(schema.date_col)
        if has_split:
            amount_cols_found = bool(schema.debit_col and schema.credit_col)
        else:
            amount_cols_found = bool(schema.amount_col)
        description_col_found = bool(
            schema.description_col or getattr(schema, "description_cols", [])
        )

        print(f"  Detected: doc_type={doc_type_detected} ({'OK' if doc_type_match else 'MISMATCH'})")
        print(f"  Convention: {convention_detected} ({'OK' if convention_match else 'MISMATCH'})")
        print(f"  Confidence: {confidence_score}")
        print(f"  Columns: date={schema.date_col}, amt={schema.amount_col}, "
              f"debit={schema.debit_col}, credit={schema.credit_col}, "
              f"desc={schema.description_col}")

        # 3. Normalize using detected schema
        transactions, skipped_rows, merge_count = _normalize_df_with_schema(
            df, schema, filename,
        )

        n_parsed = len(transactions)
        n_total_attempted = n_parsed + len(skipped_rows)

        # Compute per-field success rates
        n_amount_ok = sum(1 for t in transactions if t["amount"] is not None)
        n_date_ok = sum(1 for t in transactions if t["date"] is not None)

        normalization_rate = n_parsed / n_data_expected if n_data_expected > 0 else 0.0
        amount_success_rate = n_amount_ok / n_parsed if n_parsed > 0 else 0.0
        date_success_rate = n_date_ok / n_parsed if n_parsed > 0 else 0.0

        print(f"  Normalization: {n_parsed}/{n_data_expected} rows ({normalization_rate:.1%})")
        print(f"  Amounts OK: {n_amount_ok}/{n_parsed} ({amount_success_rate:.1%})")
        print(f"  Dates OK: {n_date_ok}/{n_parsed} ({date_success_rate:.1%})")
        if skipped_rows:
            reasons = {}
            for sr in skipped_rows:
                reasons[sr.reason] = reasons.get(sr.reason, 0) + 1
            print(f"  Skipped reasons: {reasons}")

        results.append(FileResult(
            filename=filename,
            doc_type_expected=doc_type_expected,
            doc_type_detected=doc_type_detected,
            doc_type_match=doc_type_match,
            confidence_score=confidence_score,
            convention_expected=convention_expected,
            convention_detected=convention_detected,
            convention_match=convention_match,
            n_rows_expected=n_data_expected,
            n_rows_parsed=n_parsed,
            normalization_rate=normalization_rate,
            amount_success_rate=amount_success_rate,
            date_success_rate=date_success_rate,
            date_col_found=date_col_found,
            amount_cols_found=amount_cols_found,
            description_col_found=description_col_found,
        ))

    return results


def _write_results_csv(results: list[FileResult]) -> None:
    """Write results to CSV."""
    RESULTS_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(RESULTS_PATH, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow([
            "filename", "doc_type_expected", "doc_type_detected", "doc_type_match",
            "confidence_score", "convention_expected", "convention_detected",
            "convention_match", "n_rows_expected", "n_rows_parsed",
            "normalization_rate", "amount_success_rate", "date_success_rate",
        ])
        for r in results:
            writer.writerow([
                r.filename, r.doc_type_expected, r.doc_type_detected,
                r.doc_type_match, f"{r.confidence_score:.2f}",
                r.convention_expected, r.convention_detected,
                r.convention_match, r.n_rows_expected, r.n_rows_parsed,
                f"{r.normalization_rate:.4f}", f"{r.amount_success_rate:.4f}",
                f"{r.date_success_rate:.4f}",
            ])
    print(f"\nResults written to: {RESULTS_PATH}")


def _print_summary(results: list[FileResult]) -> None:
    """Print a summary table and overall scores."""
    print(f"\n{'='*100}")
    print("  LLM IMPORT PIPELINE — RESULTS SUMMARY")
    print(f"{'='*100}")

    # Per-file table
    header = (
        f"{'File':<30} {'DocType':>8} {'Conv':>5} {'Conf':>5} "
        f"{'Rows':>10} {'Norm%':>6} {'Amt%':>5} {'Date%':>6}"
    )
    print(header)
    print("-" * len(header))
    for r in results:
        dt_mark = "OK" if r.doc_type_match else "FAIL"
        cv_mark = "OK" if r.convention_match else "FAIL"
        rows_str = f"{r.n_rows_parsed}/{r.n_rows_expected}"
        print(
            f"{r.filename:<30} {dt_mark:>8} {cv_mark:>5} {r.confidence_score:>5.2f} "
            f"{rows_str:>10} {r.normalization_rate:>5.1%} {r.amount_success_rate:>5.1%} {r.date_success_rate:>5.1%}"
        )

    # Aggregate KPIs
    n = len(results)
    if n == 0:
        print("\n  NO RESULTS")
        return

    doc_type_accuracy = sum(1 for r in results if r.doc_type_match) / n
    convention_accuracy = sum(1 for r in results if r.convention_match) / n
    avg_confidence = sum(r.confidence_score for r in results) / n
    pct_auto_import = sum(1 for r in results if r.confidence_score >= 0.80) / n
    avg_normalization = sum(r.normalization_rate for r in results) / n
    avg_amount = sum(r.amount_success_rate for r in results) / n
    avg_date = sum(r.date_success_rate for r in results) / n

    # Column mapping accuracy: date + amount + description found
    col_checks = []
    for r in results:
        checks = [r.date_col_found, r.amount_cols_found, r.description_col_found]
        col_checks.append(sum(checks) / len(checks))
    column_mapping_accuracy = sum(col_checks) / n

    print(f"\n{'='*50}")
    print(f"  AGGREGATE KPIs ({n} files)")
    print(f"{'='*50}")
    print(f"  doc_type_accuracy      : {doc_type_accuracy:.1%}")
    print(f"  convention_accuracy    : {convention_accuracy:.1%}")
    print(f"  column_mapping_accuracy: {column_mapping_accuracy:.1%}")
    print(f"  avg_confidence         : {avg_confidence:.2f}")
    print(f"  pct_auto_import (>=0.8): {pct_auto_import:.1%}")
    print(f"  avg_normalization_rate : {avg_normalization:.1%}")
    print(f"  avg_amount_success     : {avg_amount:.1%}")
    print(f"  avg_date_success       : {avg_date:.1%}")

    automation_score = (
        0.25 * doc_type_accuracy
        + 0.20 * convention_accuracy
        + 0.15 * column_mapping_accuracy
        + 0.15 * avg_confidence
        + 0.15 * avg_normalization
        + 0.05 * avg_amount
        + 0.05 * avg_date
    )
    print(f"\n  OVERALL AUTOMATION SCORE: {automation_score:.1%}")
    print(f"{'='*100}")


# ── Pytest fixtures and tests ────────────────────────────────────────────

@pytest.mark.llm
class TestLLMImport:
    """Test full LLM-assisted classification against synthetic files."""

    @pytest.fixture(scope="class")
    def manifest(self):
        """Load manifest and verify selected files exist."""
        assert MANIFEST_PATH.exists(), f"Manifest not found: {MANIFEST_PATH}"
        m = _load_manifest()
        for f in _SELECTED_FILES:
            assert f in m, f"Selected file {f} not in manifest"
            assert (GENERATED_DIR / f).exists(), f"File not found: {GENERATED_DIR / f}"
        return m

    @pytest.fixture(scope="class")
    def results(self, manifest):
        """Run the full classification + normalization pipeline on selected files."""
        res = _run_classification(manifest)
        _write_results_csv(res)
        _print_summary(res)
        assert len(res) > 0, "No results produced"
        return res

    def test_doc_type_accuracy(self, results):
        """doc_type classification accuracy should exceed 80%."""
        n = len(results)
        correct = sum(1 for r in results if r.doc_type_match)
        accuracy = correct / n
        print(f"\n  doc_type_accuracy: {correct}/{n} = {accuracy:.1%}")
        assert accuracy >= 0.80, (
            f"doc_type accuracy {accuracy:.1%} < 80%. "
            f"Failures: {[r.filename for r in results if not r.doc_type_match]}"
        )

    def test_column_mapping(self, results):
        """Column mapping accuracy (date + amount + description) should exceed 70%."""
        col_scores = []
        failures = []
        for r in results:
            checks = [r.date_col_found, r.amount_cols_found, r.description_col_found]
            score = sum(checks) / len(checks)
            col_scores.append(score)
            if score < 1.0:
                missing = []
                if not r.date_col_found:
                    missing.append("date")
                if not r.amount_cols_found:
                    missing.append("amount")
                if not r.description_col_found:
                    missing.append("description")
                failures.append(f"{r.filename}: missing {missing}")

        accuracy = sum(col_scores) / len(col_scores)
        print(f"\n  column_mapping_accuracy: {accuracy:.1%}")
        if failures:
            print(f"  Partial failures: {failures}")
        assert accuracy >= 0.70, (
            f"Column mapping accuracy {accuracy:.1%} < 70%. Failures: {failures}"
        )

    def test_convention_accuracy(self, results):
        """Sign convention detection accuracy should exceed 70%."""
        n = len(results)
        correct = sum(1 for r in results if r.convention_match)
        accuracy = correct / n
        print(f"\n  convention_accuracy: {correct}/{n} = {accuracy:.1%}")
        assert accuracy >= 0.70, (
            f"Convention accuracy {accuracy:.1%} < 70%. "
            f"Failures: {[(r.filename, r.convention_expected, r.convention_detected) for r in results if not r.convention_match]}"
        )

    def test_normalization_rate(self, results):
        """Average normalization rate (parsed rows / expected rows) should exceed 85%."""
        avg = sum(r.normalization_rate for r in results) / len(results)
        print(f"\n  avg_normalization_rate: {avg:.1%}")
        low = [(r.filename, f"{r.normalization_rate:.1%}") for r in results if r.normalization_rate < 0.50]
        assert avg >= 0.85, (
            f"Avg normalization rate {avg:.1%} < 85%. Low files: {low}"
        )

    def test_amount_success_rate(self, results):
        """Amount parsing success rate (among parsed rows) should exceed 90%."""
        avg = sum(r.amount_success_rate for r in results) / len(results)
        print(f"\n  avg_amount_success_rate: {avg:.1%}")
        assert avg >= 0.90, f"Avg amount success rate {avg:.1%} < 90%"

    def test_date_success_rate(self, results):
        """Date parsing success rate (among parsed rows) should exceed 90%."""
        avg = sum(r.date_success_rate for r in results) / len(results)
        print(f"\n  avg_date_success_rate: {avg:.1%}")
        assert avg >= 0.90, f"Avg date success rate {avg:.1%} < 90%"

    def test_confidence_scores(self, results):
        """Average confidence score should exceed 0.70."""
        avg = sum(r.confidence_score for r in results) / len(results)
        pct_auto = sum(1 for r in results if r.confidence_score >= 0.80) / len(results)
        print(f"\n  avg_confidence: {avg:.2f}")
        print(f"  pct_auto_import (>=0.80): {pct_auto:.1%}")
        assert avg >= 0.70, (
            f"Avg confidence {avg:.2f} < 0.70. "
            f"Scores: {[(r.filename, r.confidence_score) for r in results]}"
        )

    def test_no_total_failures(self, results):
        """No file should produce 0 parsed rows (total failure)."""
        total_failures = [r.filename for r in results if r.n_rows_parsed == 0]
        assert len(total_failures) == 0, (
            f"Total failures (0 rows parsed): {total_failures}"
        )
